pipeline {
    agent any
    parameters {
        choice choices:['us-west-1', 'eu-west-1', 'eu-west-2', 'sa-east-1'], description: 'Choice Zone', name: 'zonechoice'
        booleanParam(name:'Init_TERRAFORM', defaultValue: false, description: 'Check to init Terraform changes')
        booleanParam(name: 'PLAN_TERRAFORM', defaultValue: false, description: 'Check to plan Terraform changes')
        booleanParam(name: 'APPLY_TERRAFORM', defaultValue: false, description: 'Check to apply Terraform changes')
        booleanParam(name: 'DESTROY_TERRAFORM', defaultValue: false, description: 'Check to apply Terraform changes')
    }

    stages {
        stage('Clone Repository') {
            steps {
                deleteDir()
                // Clone Git repository
                // git branch: 'main',
                //     url: 'https://github.com/rahulwagh/devops-project-1.git'
            }
        }

        stage('Terraform Init') {
            steps {
                script {
                    if (params.Init_TERRAFORM) {
                        echo "=================Terraform Init=================="
                        echo "Choice : ${params.zonechoice}"
                        env.TF_VAR_zone = params.zonechoice
                        sh "export TF_VAR_zone=${env.TF_VAR_zone}"
                        sh "env | grep TF_VAR_zone"
                    }
                }
            }
        }

        stage('Terraform Plan') {
            steps {
                script {
                    if (params.PLAN_TERRAFORM) {
                        echo "=================Terraform Plan=================="
                        sh "env | grep TF_VAR_zone"
                    }
                }
            }
        }

        stage('Terraform Apply') {
            steps {
                script {
                    if (params.APPLY_TERRAFORM) {
                        echo "=================Terraform Apply=================="
                        sh "env | grep TF_VAR_zone"
                    }
                }
            }
        }

        stage('Terraform Destroy') {
            steps {
                script {
                    if (params.DESTROY_TERRAFORM) {
                        echo "=================Terraform Destroy=================="
                    }
                }
            }
        }
    }
}
